---
site_name: Arhiva Educationala Roalgo
site_url: https://roalgo.github.io/arhiva-educationala/

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.share
    - search.highlight
    - navigation.instant
    - navigation.footer
    - navigation.tabs
    - navigation.instant.progress
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
  icon:
    icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  language: ro
  font: false
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to auto mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/roalgo
      name: Hai pe discord!
  generator: false

copyright: >
  Accest conținut este licențiat sub CC BY-NC-SA 4.0 și EUPL v1.2. Pentru mai
  multe detali consultă <a href="/arhiva-educationala/licenta">pagina de licență
  </a>.

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

repo_url: https://github.com/roalgo-discord/arhiva-educationala
repo_name: roalgo-discord/arhiva-educationala
edit_uri: edit/main/docs/

plugins:
  - search
  - awesome-pages
  - tags
  - social:
      enabled: !ENV [CI, false]
      cards_layout_options:
        font_family: Roboto
        font_variant: Condensed

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
